#!/usr/bin/perl -w

use strict;
use IO::Socket;
use scigen;

print "about to use port $scigen::SCIGEND_PORT\n";
my $server = IO::Socket::INET->new( Proto => 'tcp', 
				    LocalPort => $scigen::SCIGEND_PORT,
				    Listen => 1, Reuse => 1);

die "Cannot start $0 on port $scigen::SCIGEND_PORT" unless $server;

my $client;
my $name_dat = {};
my $name_RE = undef;
my $tex_dat = {};
my $tex_RE = undef;

&initialize();

print "Initialized . . .\n";

while(1) {

    while( $client = $server->accept() ) {

	while( <$client> ) {
	    select $client;
	    print &get_system_name() . "\n";
	    close $client; 
	    last;
	}

    }

    next if $!{EINTR};
    last;

}


sub initialize {

    my $fh = new IO::File( "<system_names.in" );
    &scigen::read_rules( $fh, $name_dat, \$name_RE, 0 ); 

    $fh = new IO::File( "<scirules.in" );
    &scigen::read_rules( $fh, $tex_dat, \$tex_RE, 0 );

}

sub get_system_name {

    my $name = &scigen::generate ($name_dat, "SYSTEM_NAME", $name_RE, 0, 0);
    chomp($name);

    # how about some effects?
    my $rand = rand;
    if( $rand < .1 ) {
	$name = "{\\em $name}";
    } elsif( length($name) <= 6 and $rand < .4 ) {
	$name = uc($name);
    }

    return $name;
}
